config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :items, only: [:index, :show, :new, :create] do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
  end

  def create
    Item.create(name: params['name'], description: params['description'], price: params['price'], quantity: params['quantity'])
    redirect_to items_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/index.html.erb
<% @items.each do |item| %>
  <p><%= link_to  "#{item.name}", item_path(item.id) %></p>
<% end %>

<%= link_to  "Add Item", new_item_path %>

app/views/items/new.html.erb
<h1>Create New Item</h1>
</br>

<%= form_with model: @item, url: items_path, method: :post, local: true do |form| %>
  <p><%= form.label :name, 'Name' %>
  <%= form.text_field :name %></p>

  <p><%= form.label :description, 'Description' %>
  <%= form.text_field :description %></p>

  <p><%= form.label :price, 'Price' %>
  <%= form.text_field :price %></p>

  <p><%= form.label :quantity, 'quantity' %>
  <%= form.text_field :quantity %></p>

  <%= form.submit 'Create Item' %>
<% end %>

app/views/items/show.html.erb
<p><%= @item.name %></p>
<p><%= @item.description %></p>
<p><%= @item.price %></p>
<p><%= @item.quantity %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopifyChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>